# Generated by Django 4.0.5 on 2023-03-07 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GymApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_muscle_group', models.IntegerField(choices=[(1, 'Chest'), (2, 'Back'), (3, 'Arms'), (4, 'Abdominals'), (5, 'Legs'), (6, 'Shoulders')], default=1)),
                ('muscle_group', models.IntegerField(choices=[(1, 'Calves'), (2, 'Hamstrings'), (3, 'Quadriceps'), (4, 'Glutes'), (5, 'Biceps'), (6, 'Triceps'), (7, 'Forearms'), (8, 'Trapezius'), (9, 'Latisimus')], default=5)),
                ('equipment', models.IntegerField(choices=[(1, 'Machine'), (2, 'Darbell'), (3, 'Dumbell'), (4, 'Bodyweight'), (5, 'Cables')], default=2)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(null=True)),
                ('preworkout', models.BooleanField()),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField()),
                ('weight', models.FloatField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymApi.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ManyToManyField(to='GymApi.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymApi.session')),
            ],
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
        migrations.AddField(
            model_name='set',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GymApi.training'),
        ),
    ]
