# Generated by Django 4.0.5 on 2023-03-07 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GymApi', '0002_exercise_session_set_training_delete_workout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='training',
        ),
        migrations.AddField(
            model_name='set',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GymApi.session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
