# Generated by Django 4.0.5 on 2023-03-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApi', '0003_remove_set_training_set_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='set_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Calves'), (2, 'Hamstrings'), (3, 'Quadriceps'), (4, 'Glutes'), (5, 'Biceps'), (6, 'Triceps'), (7, 'Forearms'), (8, 'Trapezius'), (9, 'Latisimus')], default=5),
        ),
    ]
