# Generated by Django 4.0.5 on 2023-03-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApi', '0004_set_created_at_set_set_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
