# Generated by Django 4.0.5 on 2023-03-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApi', '0005_alter_set_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='set_count',
            field=models.IntegerField(),
        ),
    ]
