# Generated by Django 4.0.5 on 2023-03-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GymApi', '0006_alter_set_set_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=6)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('parentGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GymApi.musclegroup')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='TrainDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('muscle_groups', models.ManyToManyField(to='GymApi.musclegroup')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GymApi.location'),
        ),
        migrations.AddField(
            model_name='session',
            name='trainday',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GymApi.trainday'),
        ),
    ]
