# Generated by Django 4.0.5 on 2023-03-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GymApi', '0007_location_musclegroup_session_created_at_trainday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle_group_old',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Calves'), (2, 'Hamstrings'), (3, 'Quadriceps'), (4, 'Glutes'), (5, 'Biceps'), (6, 'Triceps'), (7, 'Forearms'), (8, 'Trapezius'), (9, 'Latisimus')], default=5),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GymApi.musclegroup'),
        ),
        migrations.AlterField(
            model_name='musclegroup',
            name='parentGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GymApi.musclegroup'),
        ),
        migrations.AlterField(
            model_name='session',
            name='trainday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GymApi.trainday'),
        ),
    ]
