# Generated by Django 4.0.5 on 2023-03-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GymApi', '0008_exercise_muscle_group_old_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='major_muscle_group',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_group_old',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_group',
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.ManyToManyField(to='GymApi.musclegroup'),
        ),
    ]
