# Generated by Django 4.0.5 on 2023-03-31 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GymApi', '0012_equipment_created_by_exercise_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='cardio',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.ManyToManyField(blank=True, null=True, to='GymApi.equipment'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.ManyToManyField(blank=True, null=True, to='GymApi.musclegroup'),
        ),
        migrations.AlterField(
            model_name='trainday',
            name='Exercises',
            field=models.ManyToManyField(blank=True, null=True, to='GymApi.exercise'),
        ),
        migrations.AlterField(
            model_name='trainday',
            name='muscle_groups',
            field=models.ManyToManyField(blank=True, null=True, to='GymApi.musclegroup'),
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('height', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardioSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('distance', models.FloatField()),
                ('resistanceNiveau', models.IntegerField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('device', models.CharField(default='Auto', max_length=250)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GymApi.exercise')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GymApi.session')),
            ],
        ),
    ]
