# Generated by Django 4.0.5 on 2023-03-31 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GymApi', '0013_exercise_cardio_alter_exercise_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='name',
        ),
    ]
