# Generated by Django 4.0.5 on 2023-04-02 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GymApi', '0014_remove_personalinformation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercises', models.ManyToManyField(blank=True, null=True, to='GymApi.exercise')),
                ('muscle_groups', models.ManyToManyField(blank=True, null=True, to='GymApi.musclegroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='trainday',
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='createad_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='TrainDay',
        ),
        migrations.AddField(
            model_name='session',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GymApi.training'),
        ),
    ]
